services:
  frontend:
    container_name: ns-nginx-frontal
    image: ghcr.io/fvgtekken/ns-nginx-frontal:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./nginx/rules:/etc/nginx/rules
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my-network-front
networks:
  my-network-front:
    name: default-network-front
    driver: bridge
